name: R1S_H5_pass-002

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  #REPO_URL: https://github.com/coolsnowwolf/lede
  #REPO_BRANCH: master
  #FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: config.lede
  DIY_P2_SH: diy-p2.sh
  DIY_P3_SH: diy-p3.sh
  DIY_P4_SH: diy-p4.sh
  #UPLOAD_BIN_DIR: false
  #UPLOAD_FIRMWARE: true
  #UPLOAD_COWTRANSFER: false
  #UPLOAD_WETRANSFER: false
  #UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          # 第一部分：环境部署和源码下载
          chmod +x $DIY_P2_SH
          $GITHUB_WORKSPACE/$DIY_P2_SH

      - name: Plug-in for lede integration
        run: |
          # 第二部分：调整代码
          chmod +x $DIY_P3_SH
          cd h5
          $GITHUB_WORKSPACE/$DIY_P3_SH

      - name: Build OpenWrt & Build SD img
        run: |
          # 第三部分：编译WRT和生成R1S固件
          chmod +x $DIY_P4_SH
          cd h5/friendlywrt
          $GITHUB_WORKSPACE/$DIY_P4_SH

      - name: SSH connection to Actions
        uses: Dboykey/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

      - name: Assemble Artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          find h5/out/ -name "FriendlyWrt*" | xargs -i mv -f {} ./artifact/
          find h5/friendlywrt/bin/ -name "openwrt-sunxi-cortexa53-*-squashfs-sdcard.img.gz" | xargs -i mv -f {} ./artifact/

          #添加打包代码的命令进来，再添加发布到release的代码在后面

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          # 压缩打包并提供下载
          name: FriendlyWrt_NanoPi-R1S H5 Lean
          path: ./artifact/

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 3
